TravelPouch/travelpouch

README.md

This pull request introduces a link to the Figma project within the README.md file of our repository. By including this link, we aim to improve accessibility for all team members and staff, ensuring that the design resources are available for reference.

docs: add figma link in the README.md

---

README.md

This updates the README.md file by including a preliminary description of the application. 
This is a necessary for the warmup phase.

Add Detailed Application Description to README.md

---

README.md

This add naming convention to the project. Every team member should make sure to read it

docs: Add naming convention to Readme

---

app/build.gradle.kts
app/src/main/java/com/github/se/travelpouch/model/TravelContainer.kt
app/src/test/java/com/github/se/travelpouch/TravelContainerUnitTest.kt
gradle/libs.versions.toml

Basic implementation for the Travel data model as well as related classes.
Unit Tests that checks basic requirements, and addition of necessary dependency is added.
This is necessary for user stories #8 #14 #10 to have a common base. 
Details are open to change but the overall structure should stay the same.
Closes #15

feat: add TravelContainer class, Firebase dependency and unit tests

---

.github/workflows/apk.yml

fix(APK): fixed build APK

---

.github/workflows/apk.yml

This commit add the automatic release in the CI

fix(apk): add release in the CI

---

.github/workflows/apk.yml

Added the apk in the release generated by the CI.

fix(apk): add asset in the CI release

---

.github/workflows/apk.yml

Added parameters to create release. This can fix the CI.

ci(apk): add parameters to Create Release

---

.github/workflows/apk.yml

Added all write permissions to create a release automatically with the CI.

ci(apk): add all permissions to execute the CI

---

.github/workflows/apk.yml

Changed the path to the apk file in the upload release asset.

ci(apk): change asset path with correct apk file

---

app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/NextActivitiesBanner.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt

This feature adds a semi-transparent banner that lists all activities that are due within 24 hours. This banner can be dismissed by clicking on a small cross.
This should meet the criterias for task #80
This closes #80

Latest activities reminder banner #80

---

app/src/androidTest/java/com/github/se/travelpouch/ui/documents/DocumentListTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/home/CalendarScreenTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/home/TravelListScreenTest.kt
app/src/main/java/com/github/se/travelpouch/model/documents/DocumentRepository.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/Calendar.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentList.kt
app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
app/src/main/java/com/github/se/travelpouch/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt

Created a new composable function `BottomNavigationMenu` to handle bottom navigation. Updated `TravelListScreen`, `CalendarScreen`, and `TravelActivitiesScreen` to use the new `BottomNavigationMenu` composable.

refactor(navigation): generalize BottomNavigationMenu

---

.firebaserc
.github/workflows/ci.yml
.gitignore
app/src/androidTest/java/com/github/se/travelpouch/helper/FileDownloaderTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/github/se/travelpouch/helper/FileDownloader.kt
app/src/main/res/xml/network_security_config.xml
firebase.json
storage.rules

Some code from last week missed some test. This add the tests for the FileDownloader.
This PR also add the Firestore emulator in the CI.
To run the test assertFileDownload you can't use the physical device on USB.

test: add test for FileDownloader

---

app/src/androidTest/java/com/github/se/travelpouch/ui/documents/DocumentListTest.kt
app/src/main/java/com/github/se/travelpouch/model/documents/DocumentViewModel.kt
app/src/test/java/com/github/se/travelpouch/model/profile/ProfileModelViewTest.kt
app/src/test/java/com/github/se/travelpouch/model/profile/ProfileRepositoryTest.kt

Due to an emergency we had to comment some tests on profile repository. Now, there signature was updated. There msut be merged

Fix : Recovering the profile repository tests

---

app/src/main/AndroidManifest.xml

Updated the name of the app to TravelPouch instead of MainActivity

fix: update the name app to TravelPouch

---

.github/workflows/ci.yml

Cloud sonar coverage is faulty with the new CI. We thus want to revert to the older one to have correct coverage number

Revert to older CI

---

.github/workflows/apk.yml

Description: I forgot to add the environment variable for passwords and alias for assembly

Ci: Add password environment variables

---

app/src/main/java/com/github/se/travelpouch/MainActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/Calendar.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/NextActivitiesBanner.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentPreview.kt
app/src/main/java/com/github/se/travelpouch/ui/home/AddTravel.kt
app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
app/src/main/java/com/github/se/travelpouch/ui/profile/ModifyingProfileScreen.kt
app/src/main/java/com/github/se/travelpouch/ui/profile/ProfileScreen.kt
app/src/main/java/com/github/se/travelpouch/ui/theme/Theme.kt
app/src/main/java/com/github/se/travelpouch/ui/theme/Type.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantListScreen.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantRow.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/RoleDialog.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/TruncatedText.kt

Copied from #191
Description: Create a common theme so that there's more colour and font consistency inside the application and use it wherever necessary.
Acceptance Criteria:
Theme must specify dark/bright modes that make sense
Theme must specify fonts and different sizes
Must be inside the app in places that make sense in terms of UI

UI theme and coherency

---

app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationScreenTest.kt
app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt

copied from #211
Description:
Notifications screen was merged during the last sprint without taking into account light/dark theme and UI coherency across the application.
Acceptance Criteria:
- Notifications screen should comply with the dark/light theme in terms of contrast and text.
- Top bar should be the same as other screens

UI: Fix notification screen light/dark theme handling and UI coherency 

---

app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/AddActivityScreenTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/EditActivityScreenTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/documents/DocumentPreviewTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/home/CalendarScreenTest.kt
app/src/main/java/com/github/se/travelpouch/MainActivity.kt
app/src/main/java/com/github/se/travelpouch/model/activity/Activity.kt
app/src/main/java/com/github/se/travelpouch/model/activity/ActivityRepositoryFirebase.kt
app/src/main/java/com/github/se/travelpouch/model/documents/DocumentRepository.kt
app/src/main/java/com/github/se/travelpouch/model/documents/DocumentViewModel.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/CalendarViewComposable.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentPreview.kt
app/src/main/java/com/github/se/travelpouch/ui/navigation/SwipePager.kt
app/src/test/java/com/github/se/travelpouch/model/activity/ActivityModelViewUnitTest.kt
app/src/test/java/com/github/se/travelpouch/model/activity/ActivityRepositoryUnitTest.kt
app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
app/src/test/java/com/github/se/travelpouch/model/documents/DocumentRepositoryTest.kt
app/src/test/java/com/github/se/travelpouch/model/documents/DocumentViewModelTest.kt

In this PR we link finalise the linking between existing documents to activities.

feat: Implementing the linking between documents and activities

---

app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationItemTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationScreenTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/profile/ProfileEditTest.kt
app/src/androidTest/java/com/github/se/travelpouch/ui/travel/ParticipantListScreenTest.kt
app/src/main/java/com/github/se/travelpouch/MainActivity.kt
app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepository.kt
app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryFirestore.kt
app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationViewModel.kt
app/src/main/java/com/github/se/travelpouch/model/notifications/push/PushNotificationService.kt
app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepository.kt
app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryFirebase.kt
app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryMock.kt
app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
app/src/main/java/com/github/se/travelpouch/ui/profile/ModifyingProfileScreen.kt
app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantListScreen.kt
app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryFirestoreUnitTest.kt
app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationViewModelUnitTest.kt

This PR focuses on adding callbacks to notification view model (only to the function send notification), so that we improve the coherency of the Toasts being displayed

Fix: Adding callbacks to notification view model
